#! /bin/sh -eu

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi


profile=/nix/var/nix/profiles/per-container/$1
gcroots=/nix/var/nix/gcroots/per-container/$1
root=/var/lib/machines/$1

config=$(nix build .#nixosConfigurations.x86_64-linux.container.config.system.build.toplevel --print-out-paths --no-link)

mkdir -p $profile /nix/var/nix/gcroots/per-container/$1
nix-env --set $config --profile $profile/system

mkdir -p $root

systemd-nspawn \
  --machine $1 \
  --directory $root \
  --bind-ro=/nix/store \
  --bind-ro=/nix/var/nix/db \
  --bind-ro=/nix/var/nix/daemon-socket \
  --bind="$profile:/nix/var/nix/profiles" \
  --bind="$gcroots:/nix/var/nix/gcroots" \
  $config/init
